# TODO: Make this action take environment (staging / prod) as input and use secrets, s3_bucket, etc. accordingly.
# Rename to just deploy.yml
# ------------------------------------------
# Workflow name
name: Staging Deployment

# This allows manual start of the pipeline as needed.
on:
  push:
    branches:
      - main

# The list of jobs to run
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:

      # 1. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.STAGING_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.STAGING_AWS_REGION }}

      # 2. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      # 3. Copy to S3 bucket.
      - name: Copy to S3 Bucket
        run: |
          aws s3 cp . s3://${{ vars.STAGING_S3_BUCKET }} --recursive

      # 4. Invalidate cloudfront distribution
      - name: Invalidate cloudfront distribution
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.STAGING_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'